### ISSUE TITLE
Objects with no magnitude display as 0.0 mag

### ISSUE THREAD

**Issue by MTBehnke** [MTBehnke/NightSkyGuide#54]
Currently the only object in the database without a magnitude is C99 Coalsack (dark nebula).  Should leave as blank.

**Comment by TiiXel** [comment]
@MTBehnke I can fix this but I'll need access to the database. I'm not sure it's packaged in this git repository. Could you guide me in editing it?

**Comment by MTBehnke** [comment]
The database is under src>main>assets>databases. https://github.com/MTBehnke/NightSkyGuide/tree/master/app/src/main/assets/databases

Can't you just check if mag is null, then leave magnitude blank?

**Comment by TiiXel** [comment]
That's what I'm planning to do, but C99 magnitude column is not set to NULL in the database I believe. Maybe it is, I'll check that!
